"""Technique 6: the one point two grounds are tied at, and the board that never says where.

`docs/stitch-plan.md` S3. The whole statement writes **no copper** — see `language.Bridge` for the
two judges a copper tie would each need an exemption from, and `docs/stitch-plan.md` §8 item 4 for
why it is refused rather than exempted. So every test here is about what pcbc *says*, and the one
thing it must not do is change what pcbc writes: `netcheck.py` has a zero diff in this slice and
`test_bridge_needs_no_gate_change` is the assertion that keeps it that way.

Every board is read **read-only**, including the DS2 Addon's, which lives outside this repo. Nothing
in `~/Documents/MaD` is written by this suite, and nothing here reads `examples/**/layout/` — a
placed board is generated by `conftest.placed_board` (pure Python, no KiCad) and a routed one is
marked `kicad` + `krt` and skipped when the artifact is absent.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from pcbc.build import _bridge_gate, build_job
from pcbc.circuit import _untied_grounds, check_design
from pcbc.compile import compile_design
from pcbc.copper_bar import copper_bar
from pcbc.language import load_board
from boardtext import feet_of_text
from pcbc.route_checks import build_ctx, check_bridge
from pcbc.route_verify import bridge_ties

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
FIXTURE = ROOT / "tests" / "fixtures" / "bridge" / "bridge.py"
DS2 = Path.home() / "Documents" / "MaD" / "Hardware" / "DS2Addon" / "pcbc"
HAS_DS2 = (DS2 / "ds2_addon.py").exists()
DS2_ROUTED = DS2 / "layout" / "ds2_addon" / "routed" / "layout.kicad_pcb"


def _board(name: str) -> Path:
    if name == "ds2":
        return DS2 / "ds2_addon.py"
    if name == "bridge":
        return FIXTURE
    return EXAMPLES / name / f"{name}.py"


def _placed(name: str) -> Path:
    from conftest import placed_board

    return placed_board(name, _board(name))


def _write(tmp_path: Path, name: str, body: str) -> Path:
    p = tmp_path / f"{name}.py"
    p.write_text(body)
    return p


HEAD = '''from pcbc import Board, Bridge, Capacitor, Ground, NetReq, Place, Power, Resistor, SchPlace
V33 = Power("3V3")
GND = Ground("GND")
VDDA = Power("VDDA")
VSS = Ground("VSS")
c = dict(package="0805", manufacturer="Yageo", mpn="CC0805KRX7R9BB104", lcsc="C49678")
r = dict(package="0805", manufacturer="UniOhm", mpn="0805W8F0000T5E", lcsc="C17888")
'''
TAIL = '''Board(width=40, height=25, layers=2, stackup="jlcpcb_2l_1oz")
NetReq("3V3", "GND", "VDDA", "VSS", kind="power", volts=3.3, amps=0.1)
'''


# ---------------------------------------------------------------------------------------------
# What `Bridge()` refuses, and where each refusal lives
# ---------------------------------------------------------------------------------------------


@pytest.mark.parametrize(
    "call,says",
    [
        ('Bridge("GND", "GND", at="R11")', "same net"),
        ('Bridge("GND", "VSS", at="R11", kind="weld")', "not one of"),
        ('Bridge("GND", "VSS", at=("J1.2", "J2.2"))', "names one part"),
        ('Bridge("GND", "VSS", at=("J1.2",), kind="off_board", why="x")', "two pads that leave the board"),
        ('Bridge("GND", "VSS", at=("J1", "J2"), kind="off_board", why="x")', "two pads that leave the board"),
        ('Bridge("GND", "VSS", at=("J1.2", "J2.2"), kind="off_board")', "needs why="),
    ],
)
def test_load_refuses_a_bridge_that_is_wrong_about_itself(tmp_path: Path, call: str, says: str):
    """Everything that is a property of the **call** is refused at load, before any net exists.

    Not the net names: `Chain()`, `Bus()` and `Guard()` all defer those to `compile_constraints`, and
    a board is free to write its `Bridge()` line above its `Ground()` lines. Refusing an undeclared
    net at load would turn that ordering into an error about the wrong thing.
    """
    from pcbc.language import check_board

    board = _write(tmp_path, "b", HEAD + 'Resistor("R11", "0R", p1=VSS, p2=GND, **r)\n' + TAIL + call + "\n")
    fails = check_board(board)
    assert any(says in f for f in fails), fails


@pytest.mark.parametrize(
    "call,says",
    [
        ('Bridge("GND", "NOPE", at="R11")', "no net 'NOPE'"),
        ('Bridge("GND", "3V3", at="R11")', 'write Ground("3V3")'),
    ],
)
def test_compile_refuses_a_bridge_that_is_wrong_about_the_netlist(tmp_path: Path, call: str, says: str):
    from pcbc.language import check_board

    board = _write(tmp_path, "b", HEAD + 'Resistor("R11", "0R", p1=VSS, p2=GND, **r)\n' + TAIL + call + "\n")
    assert any(says in f for f in check_board(board)), check_board(board)


def test_compile_refuses_the_same_pair_bridged_twice(tmp_path: Path):
    from pcbc.language import check_board

    body = HEAD + 'Resistor("R11", "0R", p1=VSS, p2=GND, **r)\nResistor("R12", "0R", p1=VSS, p2=GND, **r)\n' + TAIL
    board = _write(tmp_path, "b", body + 'Bridge("GND", "VSS", at="R11")\nBridge("GND", "VSS", at="R12")\n')
    assert any("already bridged on line" in f for f in check_board(board)), check_board(board)


def test_check_design_refuses_a_tie_that_is_not_a_two_pin_part(tmp_path: Path):
    """The load-bearing rule of the whole statement, and the DS2 Addon is why it exists.

    `U1` there binds both grounds on sixteen pins. A part current goes *through* is a tie; a part
    referenced to both is what makes the split matter, and reading the second as the first would
    have declared the DS2 Addon tied.
    """
    from pcbc.language import check_board

    body = HEAD + 'Capacitor("C1", "100nF", p1=VDDA, p2=VSS, **c)\nResistor("R1", "1k", p1=GND, p2=VSS, **r)\n' + TAIL
    board = _write(tmp_path, "b", body + 'Bridge("GND", "VSS", at="C9")\n')
    assert any("no part C9" in f for f in check_board(board))


def test_check_design_refuses_a_second_part_joining_the_same_two_grounds(tmp_path: Path):
    from pcbc.language import check_board

    body = HEAD + 'Resistor("R11", "0R", p1=VSS, p2=GND, **r)\nResistor("R12", "0R", p1=VSS, p2=GND, **r)\n' + TAIL
    board = _write(tmp_path, "b", body + 'Bridge("GND", "VSS", at="R11")\n')
    assert any("also join" in f and "not one point" in f for f in check_board(board)), check_board(board)


def test_check_design_refuses_a_tie_whose_pads_are_not_one_per_net(tmp_path: Path):
    from pcbc.language import check_board

    body = HEAD + 'Resistor("R11", "0R", p1=V33, p2=GND, **r)\nCapacitor("C1", "100nF", p1=VDDA, p2=VSS, **c)\n' + TAIL
    board = _write(tmp_path, "b", body + 'Bridge("GND", "VSS", at="R11")\n')
    assert any("not one pad on GND and one on VSS" in f for f in check_board(board)), check_board(board)


def test_a_capacitor_tie_is_a_note_and_not_a_refusal(tmp_path: Path):
    """An AC bridge is a real choice on an isolated domain and a mistake on a shared one, and pcbc
    cannot tell which this is. So it says the consequence and does not stop the board."""
    from pcbc.language import check_board

    body = HEAD + 'Capacitor("C9", "100nF", p1=VSS, p2=GND, **c)\n' + TAIL
    board = _write(tmp_path, "b", body + 'Bridge("GND", "VSS", at="C9", kind="cap")\n')
    notes: list[str] = []
    assert [f for f in check_board(board, pcb=False, notes=notes) if "Bridge" in f] == []
    assert any("AC bridge" in n and "no DC reference" in n for n in notes), notes


def test_off_board_refuses_a_pad_that_is_not_on_the_net_it_is_written_for(tmp_path: Path):
    from pcbc.language import check_board

    body = HEAD + 'Capacitor("C1", "100nF", p1=VDDA, p2=VSS, **c)\nCapacitor("C3", "100nF", p1=V33, p2=GND, **c)\n' + TAIL
    board = _write(tmp_path, "b", body + 'Bridge("GND", "VSS", at=("C1.2", "C3.2"), kind="off_board", why="chassis stud")\n')
    assert any("C1.2 is not a pad of GND" in f for f in check_board(board)), check_board(board)


# ---------------------------------------------------------------------------------------------
# The finding that needs no declaration, which is the one the DS2 Addon needs
# ---------------------------------------------------------------------------------------------


@pytest.mark.skipif(not HAS_DS2, reason="needs the DS2 Addon board (read-only, outside this repo)")
def test_ds2_prints_the_untied_grounds_move_and_does_not_fail():
    """A move, exit 0, on a board that builds to fab today.

    Promoting it to a failure is the job of the PR that shows the DS2 Addon tied — H.3's promotion
    procedure. Stopping a shipping board on a defect its author has not been told about is how an AI
    learns to reach for `--force`.
    """
    design = load_board(_board("ds2"))
    notes: list[str] = []
    fails = check_design(design, pcb=True, notes=notes)
    assert fails == []
    assert len(notes) == 1
    move = notes[0]
    assert move.startswith("GND/VSS: VSS cannot reach GND.")
    assert "U1 binds both on 16 pins (AVSS on VSS, DGND on GND), which is not a tie" in move
    assert "(GND: C5, C6; VSS: C1, C10, C12, C3, C4, C7, C9)" in move
    assert 'Resistor("R11", "0R", p1=GND, p2=VSS)' in move
    assert 'Bridge("GND", "VSS", at=("J1.2", "J2.2"), kind="off_board"' in move


@pytest.mark.parametrize("name", ["blinky", "buck", "c3_usb", "node"])
def test_the_example_boards_say_nothing_about_bridges(name: str):
    """Silent for a structural reason and not a tuned one: each example declares exactly one
    `Ground()`, so the pair loop has nothing to iterate."""
    design = load_board(_board(name))
    grounds = [n.name for n in design.nets.values() if n.kind == "ground"]
    assert len(grounds) == 1, grounds
    assert _untied_grounds(design) == []
    job = compile_design(design)
    ctx = build_ctx(design, job, feet_of_text(design, _placed(name).read_text()))
    assert check_bridge(ctx) == []
    assert job.constraints.bridges == ()


# ---------------------------------------------------------------------------------------------
# What the placement says: no axis separates them, and where a tie would go
# ---------------------------------------------------------------------------------------------

# The four-axis overlap of the DS2 Addon's two grounds, recorded 2026-09-21 from a **freshly placed**
# board (`conftest.placed_board`), as (axis, GND interval, VSS interval, overlap) in mm. The
# projection is of pad centres: a centre interval is contained in its box interval, so an overlap of
# centres implies an overlap of boxes and never the reverse — the conservative direction for a test
# whose claim is "no straight line separates these two domains". Measured on boxes for comparison:
# 26.180 / 16.394 / 22.679 / 18.653 mm, every one of them larger.
#
# These are `docs/stitch-plan.md` §2(n)'s own four numbers, reproduced exactly. What did **not**
# reproduce is the sentence beside them there — "GND's interval is strictly INSIDE VSS's on all four
# axes" is true of `x` and `v` and false of `y` and `u`, where GND runs past VSS's high end. The
# claim the design rests on is the weaker and true one: **all four overlap**, so there is no moat to
# cut (`docs/stitch-plan.md` §8 item 5).
DS2_AXES = (
    ("x", (13.270, 37.750), (1.520, 41.928), 24.480),
    ("y", (4.916, 24.130), (3.200, 20.360), 15.444),
    ("u", (21.058, 43.756), (13.470, 41.668), 20.610),
    ("v", (-2.291, 14.506), (-13.322, 20.195), 16.797),
)


@pytest.mark.skipif(not HAS_DS2, reason="needs the DS2 Addon board (read-only, outside this repo)")
def test_ds2_has_no_axis_that_separates_its_two_grounds():
    design = load_board(_board("ds2"))
    job = compile_design(design)
    ctx = build_ctx(design, job, feet_of_text(design, _placed("ds2").read_text()))
    moves = check_bridge(ctx)
    assert len(moves) == 1
    move = moves[0]
    assert move.startswith("GND/VSS: no axis separates the two grounds")
    for axis, gnd, vss, overlap in DS2_AXES:
        assert f"{axis} [{gnd[0]:.3f},{gnd[1]:.3f}] vs [{vss[0]:.3f},{vss[1]:.3f}] overlap {overlap:.3f} mm" in move, (axis, move)
    # Where a tie would go: the nearest pad of one to a pad of the other **on another footprint**.
    # The overall nearest GND/VSS pads are `U1.4` and `U1.5`, 0.3070 mm apart on a 0.65 mm TSSOP
    # pitch — a distance that names why the two grounds have to be tied somewhere, not a place to
    # tie them, because no part goes between two pins of one package.
    assert "J1.2 and C7.2 come closest, 2.6675 mm apart" in move
    assert 'Resistor("R11", "0R", p1=GND, p2=VSS) with Place("R11", to="J1.2")' in move


def test_the_fixture_board_says_nothing_because_its_tie_is_already_at_the_closest_approach():
    design = load_board(FIXTURE)
    job = compile_design(design)
    notes: list[str] = []
    assert check_design(design, pcb=True, notes=notes) == []
    assert notes == []
    ctx = build_ctx(design, job, feet_of_text(design, _placed("bridge").read_text()))
    assert check_bridge(ctx) == []
    spec = job.constraints.bridges[0]
    assert (spec.a, spec.b, spec.tie_ref, spec.pads) == ("GND", "VSS", "R11", ("R11.2", "R11.1"))
    assert "Bridge GND/VSS: tied at R11 kind=short, R11.2 on GND and R11.1 on VSS" in "\n".join(job.constraints.lines)


def test_a_tie_away_from_the_closest_approach_is_a_place_move(tmp_path: Path):
    """The same fixture with `R11` pushed into a corner: the two domains still meet in the middle,
    and a single-point tie in the corner makes every return current go round to reach it."""
    body = FIXTURE.read_text().replace(
        'Place("R11", position="absolute", left=18.5, top=10.5, locked=True, reason="the one tie, between the domains")',
        'Place("R11", position="absolute", left=1, top=1, locked=True, reason="deliberately not at the meeting point")',
    )
    board = _write(tmp_path, "bridge_corner", body)
    design = load_board(board)
    job = compile_design(design)
    from conftest import placed_board

    ctx = build_ctx(design, job, feet_of_text(design, placed_board("bridge_corner", board).read_text()))
    moves = check_bridge(ctx)
    assert moves, moves
    assert all(m.startswith("GND/VSS: R11 ties them at ") for m in moves), moves
    assert all("left out of the measurement on both sides" in m for m in moves), moves
    assert all('Place("R11", to=' in m for m in moves), moves


def test_two_ties_read_as_multi_before_any_copper_exists(tmp_path: Path):
    """`multi` is the one fatal verdict, and it is decided on the netlist, so a **placed** board is
    enough to reach it — which is what lets this test run without KiCad.

    It is fatal because it is the only thing here KiCad cannot see: two declared nets joined by two
    separate 0R parts are, to KiCad, two nets and two parts and no violation at all.
    """
    body = FIXTURE.read_text().replace(
        'Bridge("GND", "VSS", at="R11", why="the analog return meets the digital one under the ADC")', ""
    ).replace(
        'Capacitor("C1", "100nF", p1=VDDA, p2=VSS, **c)',
        'Capacitor("C1", "100nF", p1=VDDA, p2=VSS, **c)\nResistor("R12", "0R", package="0805", manufacturer="UniOhm", mpn="0805W8F0000T5E", lcsc="C17888", p1=VSS, p2=GND)',
    ).replace(
        'SchPlace("R11", left=60, top=40)',
        'SchPlace("R11", left=60, top=40)\nSchPlace("R12", left=60, top=80)',
    ).replace(
        'Place("C3", position="absolute", right=6, top=6, locked=True, reason="digital decoupling, east")',
        'Place("R12", position="absolute", left=18.5, top=20, locked=True, reason="the second tie this test exists for")\nPlace("C3", position="absolute", right=6, top=6, locked=True, reason="digital decoupling, east")',
    )
    board = _write(tmp_path, "bridge_multi", body)
    design = load_board(board)
    from conftest import placed_board

    text = placed_board("bridge_multi", board).read_text()
    gate = _bridge_gate(text, design)
    assert gate["verdicts"] == {"GND|VSS": "multi"}
    assert len(gate["fails"]) == 1
    assert "R11, R12 all join GND to VSS" in gate["fails"][0]


# ---------------------------------------------------------------------------------------------
# What the finished copper says
# ---------------------------------------------------------------------------------------------

# The DS2 Addon's two grounds, read off its checked-in routed board 2026-09-21.
#
# `closest` is over **copper**, not pads: the nearest approach is a GND track and a VSS via, neither
# of them a pad, which is why the placement's own answer (0.3070 mm, `U1.4` to `U1.5`) is a different
# number about a different question. `facing`/`pf` are `route_verify._coupling` at
# `COUPLING_CELL_MM` — 20.052 mm2 of VSS copper on F.Cu over the 1012.099 mm2 GND pour on B.Cu,
# across 1.53 mm of FR4 at Dk 4.6.
#
# `docs/stitch-plan.md` §6 row 6 recorded **21.600 mm2 (64.5 %) and 0.575 pF** from the panel and
# neither reproduces. The percentage does, against the wrong denominator: 20.052 mm2 is 64.5 % of
# *all* VSS copper on both layers and 76.3 % of the F.Cu half, and only the F.Cu half can face a
# B.Cu pour. These are the numbers this session measured.
DS2_TIE = {"verdict": "none", "closest": 0.2250, "facing_mm2": 20.052, "pf": 0.5338}

@pytest.mark.kicad
@pytest.mark.skipif(not DS2_ROUTED.exists(), reason="needs the DS2 Addon's routed board")
def test_ds2_routed_board_has_two_grounds_and_nothing_joining_them():
    design = load_board(_board("ds2"))
    cs = compile_design(design).constraints
    rows = bridge_ties(DS2_ROUTED.read_text(), design, cs)
    assert len(rows) == 1
    row = rows[0]
    assert (row.a, row.b, row.verdict, row.tie) == ("GND", "VSS", DS2_TIE["verdict"], "")
    assert row.closest is not None
    assert row.closest[0] == pytest.approx(DS2_TIE["closest"], abs=1e-4)
    assert row.closest[1] == "GND track on F.Cu (22.7,13.8)-(24,13.8)"
    assert row.closest[2] == "VSS via at (23.2,13.2)"
    assert row.facing_mm2 == pytest.approx(DS2_TIE["facing_mm2"], abs=0.02)
    assert row.coupling_pf == pytest.approx(DS2_TIE["pf"], abs=0.001)
    # Never fatal: the board it fires on ships and builds green.
    gate = _bridge_gate(DS2_ROUTED.read_text(), design)
    assert gate["fails"] == []
    assert gate["verdicts"] == {"GND|VSS": "none"}


@pytest.mark.kicad
def test_the_fixture_builds_to_fab_with_the_gate_verified(tmp_path: Path):
    """The whole path, on the board the DS2 Addon should be: `Bridge()` through check, schematic,
    placement, routing, KiCad's own DRC and fab, with `netcheck.check_copper` passing it and **no
    gate change at all**."""
    board = tmp_path / "bridge.py"
    board.write_text(FIXTURE.read_text())
    result = build_job(board, upto="fab", force=True)
    assert result["error"] is None, result["error"]
    assert result["ok"] is True
    route = next(s for s in result["steps"] if s["stage"] == "route")
    assert route["copper"] == "verified", route["copper"]
    assert route["bridges"]["verdicts"] == {"GND|VSS": "tied"}
    assert route["bridges"]["fails"] == []
    assert route["bridges"]["notes"] == []
    # The census entry: who ties them, the one number in the copper bar that counts no copper.
    assert route["copper_bar"]["totals"]["bridge"] == {"GND|VSS": "R11"}
    assert "copper: GND and VSS are tied at R11, and at nothing else" in route["copper_bar"]["lines"]
    # The plane branch of `_pad_fed` had a plane to read: without `NetReq("GND", kind="power")`
    # beside `Ground("GND")`, `krt_plan` writes no `gnd_pour` at all (`docs/stitch-plan.md` §7.1).
    assert route["planes"]["islands"] == {"GND B.Cu": 1}


def test_bridge_needs_no_gate_change():
    """`netcheck.copper_nets` matches `(pad "N" ... (net "NAME"))` **inside footprint blocks only**
    and never reads a `(segment)` or a `(via)`. That is the measurement the whole slice rests on: a
    tie made of a part changes no pad binding, so `compare()` passes it and `netcheck.py` has a zero
    diff. A copper tie would instead need an exemption in two judges at once — see `language.Bridge`.
    """
    from pcbc.netcheck import copper_nets

    text = (
        '(kicad_pcb\n\t(footprint "R_0805"\n\t\t(property "Reference" "R11")\n'
        '\t\t(pad "1" smd rect (at 0 0) (size 1 1) (layers "F.Cu") (net 1 "VSS"))\n'
        '\t\t(pad "2" smd rect (at 2 0) (size 1 1) (layers "F.Cu") (net 2 "GND"))\n\t)\n'
        '\t(segment (start 0 0) (end 2 0) (width 0.25) (layer "F.Cu") (net 1 "VSS"))\n'
        '\t(via (at 1 0) (size 0.8) (drill 0.4) (layers "F.Cu" "B.Cu") (net 2 "GND"))\n)'
    )
    got = copper_nets(text)
    assert got == {"VSS": {("R11", "1")}, "GND": {("R11", "2")}}


def test_copper_bar_has_an_empty_bridge_entry_when_nobody_asks():
    bar = copper_bar('(kicad_pcb\n\t(net 0 "")\n)')
    assert bar["totals"]["bridge"] == {}
