"""Layout objects to KiCad s-expressions: one Python object, one KiCad primitive, field for field.

`render` writes each `model.Copper` as the `(segment)`, `(arc)`, `(via)` or `(zone)` it is, every
field it carries in the place KiCad 10 writes it; `render_graphics` does the same for every drawing
from its schema (`layout_prims`); `emit_board` puts them on the placed board, stripped of every layout
primitive first. Nothing here decides geometry and nothing here reads a router's file:
`gen.decompile` is the only reader, and it reads KiCad's own save. Lengths are written to KiCad's
1 nm; a number KiCad keeps as a double (a ratio, an angle, an area) is written exactly.
"""

from __future__ import annotations

import re
from dataclasses import replace

from .model import Copper, Design, Graphic, Pose
from .sexp import board_footprint_spans, fmt_exact, fmt_num, footprint_reference, matching_paren, quote, stable_uuid


def _fmt(v: float) -> str:
    return fmt_num(v)


# A hand-written core `Pour` that leaves a zone number out gets it from the compiled constraints
# where `constraints.py` derives one — `clearance` is the net's class clearance, `min_thickness` the
# board's minimum track (`stackup.track_min`) — and otherwise KiCad 10's own default for a new zone
# (the pcbnew probe in `docs/layout-properties.md`): thermal gap and spoke 0.5 mm, island removal 0.
# The generator never leaves one out.
ZONE_DEFAULTS = {
    "thermal_gap": 0.5,
    "thermal_bridge_width": 0.5,
    "island_removal_mode": 0,
}
# What KiCad 10.0.6 writes for a zone handed `(fill yes (mode hatch))` and nothing else (measured with
# `kicad-cli pcb upgrade`, third review P5): the hatch fields it fills in. Filled on a hand-written
# `Pour(fill_mode="hatch")` that leaves them out, and recorded in `core_filled`, so KiCad's save reads
# back exactly what was written and the build never refuses the line for defaults it did not fill.
HATCH_DEFAULTS = {
    "hatch_thickness": 1.0,
    "hatch_gap": 1.5,
    "hatch_orientation": 0.0,
    "hatch_border_algorithm": "hatch_thickness",
    "hatch_min_hole_area": 0.15,
}


# What KiCad 10.0.6 writes for a via handed `(teardrops (enabled yes))` and nothing else (measured on
# blinky, third review P1), in its order: filled on a hand-written `Via(teardrops={...})` for every
# key the line leaves out, and recorded in `core_filled`. The teardrop zones themselves are KiCad's
# (`gen.is_teardrop_zone`): regenerated by its refill, never a layout object.
TEARDROP_DEFAULTS = {
    "best_length_ratio": 0.5,
    "max_length": 1.0,
    "best_width_ratio": 1.0,
    "max_width": 2.0,
    "curved_edges": False,
    "filter_ratio": 0.9,
    "enabled": True,
    "allow_two_segments": False,
    "prefer_zone_connections": False,
}


def _r6(v: float) -> float:
    return round(float(v), 6)


def normalise_outline(entries) -> tuple:
    """A zone outline as KiCad holds it after loading the file (measured with `kicad-cli pcb upgrade`
    on every case, third review R1): every coordinate at 1 nm, a vertex equal to the one before it
    dropped, a closing vertex equal to the first dropped, and a vertex equal to the start of the arc
    after it or the end of the arc before it dropped (the arc already carries that point). A collinear
    midpoint, a clockwise outline and a self-touching outline are kept as written. A core `Pour` is
    normalised this way before anything compares it to the router's or KiCad's copy, and the change
    is recorded in the route step's `core_filled`."""
    from .layout_prims import is_arc

    pts = [tuple(tuple(_r6(v) for v in p) for p in e) if is_arc(e) else (_r6(e[0]), _r6(e[1])) for e in entries]
    out: list = []
    for e in pts:
        if out:
            prev = out[-1]
            if e == prev:
                continue
            if not is_arc(e) and is_arc(prev) and e == prev[2]:
                continue  # the arc's end, written again
            if is_arc(e) and not is_arc(prev) and prev == e[0]:
                out.pop()  # the arc's start, written before it
        out.append(e)
    if len(out) > 1 and not is_arc(out[-1]) and not is_arc(out[0]) and out[-1] == out[0]:
        out.pop()
    if len(out) > 1 and not is_arc(out[-1]) and is_arc(out[0]) and out[-1] == out[0][0]:
        out.pop()
    return tuple(out)


def stamp(design: Design, items: list[Copper]) -> list[Copper]:
    """Fill the fields a hand-written line may omit: track width and via size/drill from the compiled
    constraint of the net, a pour's outline from the board, its clearance and minimum thickness from
    the constraints, its other numbers from KiCad's defaults (`ZONE_DEFAULTS`, and `HATCH_DEFAULTS`
    for a hatch fill), and `filled` as KiCad's refill leaves it (yes for a copper pour, no for a rule
    area). A pour's outline and holes are put in the form KiCad's load gives them
    (`normalise_outline`).

    Only `None` is filled. A value that is present is emitted as written — one below the board's
    minimum is `layout_check`'s refusal, never widened here.
    """
    from .compile import compile_design
    from .stackup import get_stackup

    def needs(c: Copper) -> bool:
        if c.kind in ("seg", "arc"):
            return c.width is None
        if c.kind == "via":
            return c.size is None or c.drill is None
        if c.kind == "pour":
            return not c.points or c.filled is None or c.clearance is None or c.min_thickness is None or (c.keepout is not None and c.placement is None) or any(getattr(c, k) is None for k in ZONE_DEFAULTS)
        return False

    if not any(needs(c) for c in items):
        return [_shaped(c) for c in items]
    job = compile_design(design)
    cs = job.constraints
    stack = get_stackup(job.stackup) if cs is not None else None
    w, h = design.board.size_mm if design.board else (0.0, 0.0)
    inset = 0.5
    out: list[Copper] = []
    for c in items:
        con = cs.by_net(c.net) if cs is not None and c.net else None
        fix: dict = {}
        if c.kind in ("seg", "arc") and c.width is None and con is not None:
            fix["width"] = con.width_mm.value
        if c.kind == "via" and con is not None:
            if c.drill is None:
                fix["drill"] = con.via.drill_mm
            if c.size is None:
                fix["size"] = con.via.diameter_mm
        if c.kind == "pour":
            if not c.points and design.board is not None:
                fix["points"] = ((inset, inset), (w - inset, inset), (w - inset, h - inset), (inset, h - inset))
            if c.keepout is not None:
                # A rule area: KiCad writes it with no clearance and its placement block switched off,
                # whatever it was handed (measured: a 0.127 clearance comes back 0).
                if c.clearance is None:
                    fix["clearance"] = 0.0
                if c.placement is None:
                    fix["placement"] = {"enabled": False, "sheetname": ""}
            elif c.clearance is None:
                fix["clearance"] = con.clearance_mm.value if con is not None else (stack.clearance_min if stack is not None else 0.5)
            if c.min_thickness is None:
                fix["min_thickness"] = stack.track_min if stack is not None else 0.25
            if c.filled is None:
                fix["filled"] = c.keepout is None
            for k, v in ZONE_DEFAULTS.items():
                if getattr(c, k) is None:
                    fix[k] = v
        out.append(_shaped(replace(c, **fix) if fix else c))
    return out


def _shaped(c: Copper) -> Copper:
    """A pour with its outline and holes in KiCad's loaded form (`normalise_outline`) and, for a hatch
    fill, the hatch fields KiCad fills in (`HATCH_DEFAULTS`); a via with teardrops with every teardrop
    parameter KiCad writes (`TEARDROP_DEFAULTS`); anything else unchanged."""
    if c.kind == "via" and c.teardrops is not None:
        unknown = set(c.teardrops) - set(TEARDROP_DEFAULTS)
        if unknown:
            raise ValueError(f"{c.where or c.id}: teardrops has no field {sorted(unknown)}; KiCad's are {list(TEARDROP_DEFAULTS)}")
        full = {k: c.teardrops.get(k, v) for k, v in TEARDROP_DEFAULTS.items()}
        return replace(c, teardrops=full) if full != c.teardrops else c
    if c.kind != "pour":
        return c
    fix: dict = {}
    if c.points:
        pts = normalise_outline(c.points)
        if pts != tuple(c.points):
            fix["points"] = pts
    if c.holes:
        holes = tuple(normalise_outline(h) for h in c.holes)
        if holes != tuple(tuple(h) for h in c.holes):
            fix["holes"] = holes
    if c.fill_mode == "hatch":
        for k, v in HATCH_DEFAULTS.items():
            if getattr(c, k) is None:
                fix[k] = v
    return replace(c, **fix) if fix else c


def uuid_of(c: Copper | Graphic, board: str) -> str:
    """The object's own `uuid`, or one derived from its `id` when the line did not write one."""
    return c.uuid or stable_uuid(board, "layout", c.id)


def _xy(tag: str, pt) -> str:
    return f"({tag} {_fmt(pt[0])} {_fmt(pt[1])})"


def _yes(v: bool) -> str:
    return "yes" if v else "no"


def _mask_layer(layer: str) -> str:
    return ("F" if layer.startswith("F.") else "B") + ".Mask"


def _track_layer(c: Copper) -> str:
    if c.solder_mask:
        return f"(layers {quote(c.layer)} {quote(_mask_layer(c.layer))})"
    return f"(layer {quote(c.layer)})"


def _seg(c: Copper, uid: str) -> str:
    lines = [_xy("start", c.a)]
    if c.kind == "arc":
        lines.append(_xy("mid", c.mid))
    lines += [_xy("end", c.b), f"(width {_fmt(c.width)})"]
    if c.locked:
        lines.append("(locked yes)")
    lines.append(_track_layer(c))
    if c.solder_mask_margin is not None:
        lines.append(f"(solder_mask_margin {_fmt(c.solder_mask_margin)})")
    if c.net is not None:
        lines.append(f"(net {quote(c.net)})")
    lines.append(f"(uuid {quote(uid)})")
    head = "segment" if c.kind == "seg" else "arc"
    return f"\t({head}\n" + "".join(f"\t\t{x}\n" for x in lines) + "\t)\n"


def _sided(tag: str, d: dict | None) -> list[str]:
    if d is None:
        return []
    return [f"({tag} " + " ".join(f"({s} {d[s]})" for s in ("front", "back") if s in d) + ")"]


def _drill(tag: str, d) -> list[str]:
    if d is None:
        return []
    size, (a, b) = d
    return [f"({tag} (size {_fmt(size)}) (layers {quote(a)} {quote(b)}))"]


def _post(tag: str, d: dict | None) -> list[str]:
    if d is None:
        return []
    parts = [f"({k} {_fmt(d[k])})" for k in ("size", "depth") if k in d]
    if "angle" in d:
        parts.append(f"(angle {fmt_exact(d['angle'])})")
    return [f"({tag} {d['mode']}" + "".join(" " + p for p in parts) + ")"]


# Every number a primitive carries that KiCad keeps as a double, not in nanometres: written exactly
# (`sexp.fmt_exact`), never cut to six decimals. Every other number is a length (`fmt_num`, 1 nm).
EXACT = frozenset({"best_length_ratio", "best_width_ratio", "filter_ratio", "hatch_orientation", "hatch_smoothing_value", "hatch_min_hole_area", "island_area_min", "angle"})


def _value(v, key: str = "") -> str:
    if isinstance(v, bool):
        return _yes(v)
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return fmt_exact(v) if key in EXACT else _fmt(v)
    return str(v)


def _via(c: Copper, uid: str) -> str:
    kind = "" if c.via_type in ("", "through") else f" {c.via_type}"
    layers = c.layers or ("F.Cu", "B.Cu")
    lines = [_xy("at", c.at), f"(size {_fmt(c.size)})", f"(drill {_fmt(c.drill)})"]
    lines += _drill("backdrill", c.backdrill) + _drill("tertiary_drill", c.tertiary_drill)
    lines += _post("front_post_machining", c.front_post_machining) + _post("back_post_machining", c.back_post_machining)
    lines.append(f"(layers {quote(layers[0])} {quote(layers[1])})")
    if c.padstack is not None:
        mode, per = c.padstack
        lines.append(f"(padstack (mode {mode}) " + " ".join(f"(layer {quote(la)} (size {_fmt(sz)}))" for la, sz in per) + ")")
    for flag in ("remove_unused_layers", "keep_end_layers", "locked", "free"):
        if getattr(c, flag):
            lines.append(f"({flag} yes)")
    if c.zone_layer_connections:
        lines.append("(zone_layer_connections " + " ".join(quote(x) for x in c.zone_layer_connections) + ")")
    lines += _sided("tenting", c.tenting)
    if c.capping is not None:
        lines.append(f"(capping {_yes(c.capping)})")
    lines += _sided("covering", c.covering) + _sided("plugging", c.plugging)
    if c.filling is not None:
        lines.append(f"(filling {_yes(c.filling)})")
    if c.teardrops is not None:
        lines.append("(teardrops " + " ".join(f"({k} {_value(v, k)})" for k, v in c.teardrops.items()) + ")")
    if c.net is not None:
        lines.append(f"(net {quote(c.net)})")
    lines.append(f"(uuid {quote(uid)})")
    return f"\t(via{kind}\n" + "".join(f"\t\t{x}\n" for x in lines) + "\t)\n"


KEEPOUT_KEYS = ("tracks", "vias", "pads", "copperpour", "footprints")
PLACEMENT_KEYS = ("enabled", "sheetname", "component_class", "group")
CONNECT_ATOM = {"thermal": "", "solid": " yes", "none": " no", "thru_hole_only": " thru_hole_only"}
FILL_KEYS = (
    "thermal_gap",
    "thermal_bridge_width",
    "smoothing",
    "radius",
    "island_removal_mode",
    "island_area_min",
    "hatch_thickness",
    "hatch_gap",
    "hatch_orientation",
    "hatch_smoothing_level",
    "hatch_smoothing_value",
    "hatch_border_algorithm",
    "hatch_min_hole_area",
)


def _pts(points) -> str:
    from .layout_prims import pts_sexp

    return "(polygon " + pts_sexp(points) + ")"


def _zone(c: Copper, uid: str) -> str:
    lines: list[str] = []
    if c.net is not None:
        lines.append(f"(net {quote(c.net)})")
    if c.locked:
        lines.append("(locked yes)")
    if c.layers is not None:
        lines.append("(layers " + " ".join(quote(x) for x in c.layers) + ")")
    else:
        lines.append(f"(layer {quote(c.layer)})")
    lines.append(f"(uuid {quote(uid)})")
    if c.name is not None:
        lines.append(f"(name {quote(c.name)})")
    lines.append(f"(hatch {c.hatch[0]} {_fmt(c.hatch[1])})")
    if c.priority is not None:
        lines.append(f"(priority {c.priority})")
    if c.teardrop_type is not None:
        lines.append(f"(attr (teardrop (type {c.teardrop_type})))")
    lines.append(f"(connect_pads{CONNECT_ATOM[c.connect]} (clearance {_fmt(c.clearance)}))")
    lines.append(f"(min_thickness {_fmt(c.min_thickness)})")
    if c.filled_areas_thickness is not None:
        lines.append(f"(filled_areas_thickness {_yes(c.filled_areas_thickness)})")
    if c.keepout is not None:
        unknown = set(c.keepout) - set(KEEPOUT_KEYS)
        if unknown:
            raise ValueError(f"{c.id}: keepout has no field {sorted(unknown)}; KiCad's are {KEEPOUT_KEYS}")
        lines.append("(keepout " + " ".join(f"({k} {c.keepout[k]})" for k in KEEPOUT_KEYS if k in c.keepout) + ")")
    if c.placement is not None:
        unknown = set(c.placement) - set(PLACEMENT_KEYS)
        if unknown:
            raise ValueError(f"{c.id}: placement has no field {sorted(unknown)}; KiCad's are {PLACEMENT_KEYS}")
        parts = []
        for k in PLACEMENT_KEYS:
            if k in c.placement:
                v = c.placement[k]
                parts.append(f"({k} {_yes(v) if isinstance(v, bool) else quote(v)})")
        lines.append("(placement " + " ".join(parts) + ")")
    fill = []
    if c.fill_mode is not None:
        fill.append(f"(mode {c.fill_mode})")
    for k in FILL_KEYS:
        v = getattr(c, k)
        if v is not None:
            fill.append(f"({k} {_value(v, k)})")
    lines.append("(fill" + (" yes" if c.filled else "") + (" " + " ".join(fill) if fill else "") + ")")
    for layer, at in (c.hatch_position or {}).items():
        lines.append(f"(property (layer {quote(layer)}) (hatch_position {_xy('xy', at)}))")
    lines.append(_pts(c.points))
    lines += [_pts(h) for h in c.holes]
    return "\t(zone\n" + "".join(f"\t\t{x}\n" for x in lines) + "\t)\n"


def render_one(c: Copper, *, board: str) -> str:
    """One stamped copper object as its KiCad primitive. Refuses an object missing a field KiCad needs."""
    uid = uuid_of(c, board)
    if c.kind in ("seg", "arc"):
        if c.a is None or c.b is None or c.width is None or (c.kind == "arc" and c.mid is None):
            raise ValueError(f"{c.id}: a {c.kind} needs its ends{' and mid' if c.kind == 'arc' else ''} and a width")
        return _seg(c, uid)
    if c.kind == "via":
        if c.at is None or c.size is None or c.drill is None:
            raise ValueError(f"{c.id}: a via needs at, size and drill")
        return _via(c, uid)
    if c.kind == "pour":
        if not c.points:
            raise ValueError(f"{c.id}: a pour needs an outline")
        return _zone(c, uid)
    raise ValueError(f"{c.id}: {c.kind!r} is not a copper primitive")


def render(design: Design, items: list[Copper], *, board: str) -> str:
    return "".join(render_one(c, board=board) for c in stamp(design, items))


def own_uuids(g: Graphic, board: str) -> dict:
    """`g`'s fields with its own uuids filled in as the emitter writes them — its own (derived from
    `id` when the line wrote none), a dimension's text's (KiCad gives it the dimension's), each table
    cell's — and its members left as ids."""
    vals = dict(g.f)
    uid = uuid_of(g, board)
    vals["uuid"] = uid
    if vals.get("gr_text") is not None and g.kind == "dimension":
        vals["gr_text"] = {**vals["gr_text"], "uuid": vals["gr_text"].get("uuid") or uid}
    if g.kind == "table":
        vals["cells"] = tuple({**c, "uuid": c.get("uuid") or stable_uuid(uid, "cell", i)} for i, c in enumerate(vals.get("cells") or ()))
    return vals


def _resolve(g: Graphic, board: str, uuids: dict[str, str] | None) -> dict:
    """`g`'s fields with every uuid a KiCad file needs filled in: its own (derived from `id` when the
    line wrote none), a dimension's text's (KiCad gives it the dimension's), each table cell's, and a
    group's members (ids to uuids, sorted, which is the order KiCad writes them in)."""
    vals = own_uuids(g, board)
    if "members" in vals:

        def one(m: str) -> str:
            if uuids is not None and m in uuids:
                return uuids[m]
            if uuids is not None:
                raise ValueError(f"{g.where or g.id}: {g.kind} member {m!r} is not the id of any layout object")
            return stable_uuid(board, "layout", m)

        vals["members"] = tuple(sorted(one(m) for m in vals["members"]))
    return vals


def render_graphics(items: list[Graphic], *, board: str, uuids: dict[str, str] | None = None) -> str:
    """Board drawings as the s-expressions KiCad 10.0.6 writes, one primitive per object, every field
    from the object (`layout_prims.SCHEMAS`; nothing here is a constant). `uuids` maps every layout
    object's id to its uuid, for group and generator members; without it a member's uuid is derived
    from its id the way `uuid_of` derives one."""
    from .layout_prims import SCHEMAS, write_node

    return "".join(write_node(SCHEMAS[g.kind], _resolve(g, board, uuids)) for g in items)


def splice(pcb_text: str, block: str) -> str:
    if not block:
        return pcb_text
    body = pcb_text.rstrip()
    if not body.endswith(")"):
        raise ValueError("not a KiCad board")
    return body[:-1].rstrip() + "\n" + block + ")\n"


_COPPER_HEAD = re.compile(r"\n\t\((segment|arc|via|zone)\b")
_LAYOUT_HEAD = re.compile(r"\n\t\((segment|arc|via|zone|gr_line|gr_rect|gr_circle|gr_arc|gr_poly|gr_curve|gr_text|gr_text_box|dimension|group|image|table|barcode|target|point|generated)\b")


def _strip(text: str, head: re.Pattern) -> str:
    out: list[str] = []
    pos = 0
    for m in head.finditer(text):
        if m.start() < pos:
            continue
        end = matching_paren(text, m.start() + 2)
        out.append(text[pos : m.start()])
        pos = end + 1
    out.append(text[pos:])
    return "".join(out)


def strip_copper(text: str) -> str:
    """The board with every top-level `(segment)`, `(arc)`, `(via)` and `(zone)` removed."""
    return _strip(text, _COPPER_HEAD)


def strip_layout(text: str) -> str:
    """The board with every top-level layout primitive removed: the copper (`strip_copper`) and every
    drawing (`gr_*`, `dimension`, `group`, `image`, `table`, `barcode`, `target`, `point`, `generated`).

    What `emit_board` starts from, so that no layout primitive of the board it writes can have come
    from anywhere but a Python object. The outline and keepout rule areas go too: they come back as
    the `Rect` and `Pour(keepout=...)` lines `layout.gen.py` carries. What stays is what the layout
    language does not own: the header, layers, setup, nets, board properties, embedded files, and the
    footprints (whose poses `set_poses` then writes from `Place`)."""
    return _strip(text, _LAYOUT_HEAD)


_AT_LINE = re.compile(r"\n\t\t\(at ([-0-9.eE+]+) ([-0-9.eE+]+)(?: ([-0-9.eE+]+))?\)")
_LAYER_LINE = re.compile(r'\n\t\t\(layer "([^"]*)"\)')
_LOCKED_LINE = re.compile(r"\n\t\t\(locked yes\)")


def _same_angle(a: float, b: float) -> bool:
    return abs(((a - b) + 180.0) % 360.0 - 180.0) < 1e-6


_XY = re.compile(r"\(xy ([-0-9.eE+]+) ([-0-9.eE+]+)\)")


def _move_footprint_zones(block: str, dx: float, dy: float) -> str:
    """Every `(xy)` inside the footprint's own `(zone ...)` children shifted by (dx, dy): KiCad keeps
    those zones' outlines and fills in absolute board coordinates."""
    out: list[str] = []
    pos = 0
    for zm in re.finditer(r"\n\t\t\(zone\b", block):
        if zm.start() < pos:
            continue
        end = matching_paren(block, zm.start() + 3) + 1
        zone = block[zm.start() : end]
        zone = _XY.sub(lambda x: f"(xy {_fmt(float(x.group(1)) + dx)} {_fmt(float(x.group(2)) + dy)})", zone)
        out.append(block[pos : zm.start()])
        out.append(zone)
        pos = end
    out.append(block[pos:])
    return "".join(out)


def set_poses(text: str, poses: list[Pose]) -> str:
    """Every footprint's `(at x y rot)`, `(layer)` and `(locked)` written from its `Pose`.

    Every footprint on the board must have exactly one pose, and every pose a footprint. A pose may
    move a footprint; it may not turn or flip it — a footprint's pads carry their own absolute angles
    and a flip mirrors all of its geometry, and that is the place stage's job and KiCad's, not a
    transcription's. Both are refused, naming the part, rather than written half-done."""
    by_ref: dict[str, Pose] = {}
    for p in poses:
        if p.ref in by_ref:
            raise ValueError(f"{p.where or 'layout'}: Place({p.ref!r}) is written twice")
        by_ref[p.ref] = p
    out: list[str] = []
    pos = 0
    seen: set[str] = set()
    for a, b in board_footprint_spans(text):
        block = text[a:b]
        ref = footprint_reference(block)
        pose = by_ref.get(ref or "")
        if pose is None:
            raise ValueError(f"footprint {ref!r} is on the placed board and has no Place() in layout.gen.py")
        seen.add(pose.ref)
        m = _AT_LINE.search(block)
        lm = _LAYER_LINE.search(block)
        if m is None or lm is None:
            raise ValueError(f"footprint {ref!r} has no (at) or (layer) of its own")
        if lm.group(1) != pose.layer:
            raise ValueError(f"{pose.where or ref}: Place({ref!r}) puts it on {pose.layer} and the placed board has it on {lm.group(1)}; flipping a part is the place stage's (board.py), not the layout file's")
        if not _same_angle(float(m.group(3) or 0.0), pose.rot):
            raise ValueError(f"{pose.where or ref}: Place({ref!r}) turns it to {pose.rot:g} and the placed board has {float(m.group(3) or 0):g}; rotating a part is the place stage's (board.py), not the layout file's")
        rot = f" {fmt_exact(pose.rot)}" if not _same_angle(pose.rot, 0.0) else ""
        dx, dy = pose.at[0] - float(m.group(1)), pose.at[1] - float(m.group(2))
        block = block[: m.start()] + f"\n\t\t(at {_fmt(pose.at[0])} {_fmt(pose.at[1])}{rot})" + block[m.end() :]
        if abs(dx) > 1e-9 or abs(dy) > 1e-9:
            # KiCad stores a footprint's own zones in board coordinates, not the footprint's: its
            # editor moves them with the part, so a move written here moves them too.
            block = _move_footprint_zones(block, dx, dy)
        locked = _LOCKED_LINE.search(block)
        if pose.locked and locked is None:
            lm = _LAYER_LINE.search(block)
            block = block[: lm.start()] + "\n\t\t(locked yes)" + block[lm.start() :]
        elif not pose.locked and locked is not None:
            block = block[: locked.start()] + block[locked.end() :]
        out.append(text[pos:a])
        out.append(block)
        pos = b
    out.append(text[pos:])
    extra = sorted(set(by_ref) - seen)
    if extra:
        raise ValueError(f"Place() names {', '.join(extra)}, which the placed board does not have")
    return "".join(out)


def emit_board(placed_text: str, poses: list[Pose], copper: list[Copper], graphics: list[Graphic], *, design: Design, board: str) -> str:
    """The final board: the placed board's footprints, header and setup, every layout primitive
    stripped (`strip_layout`), every footprint posed from its `Place`, and every copper primitive and
    drawing rendered from its Python object. The one writer of the file every later stage reads."""
    from collections import Counter

    objs: list[Copper | Graphic] = [*copper, *graphics]
    uids = Counter(uuid_of(c, board) for c in objs)
    dup = sorted(u for u, n in uids.items() if n > 1)
    if dup:
        who = [c.where or c.id for c in objs if uuid_of(c, board) == dup[0]]
        raise ValueError(f"two layout objects carry the same uuid {dup[0]} ({', '.join(who)}); KiCad would silently re-key one")
    ids = Counter(c.id for c in objs)
    twice = sorted(i for i, n in ids.items() if n > 1)
    if twice:
        who = [c.where or c.id for c in objs if c.id == twice[0]]
        raise ValueError(f"two layout objects carry the id {twice[0]!r} ({', '.join(who)})")
    uuids = {c.id: uuid_of(c, board) for c in objs}
    text = set_poses(strip_layout(placed_text), poses)
    return splice(text, render(design, copper, board=board) + render_graphics(graphics, board=board, uuids=uuids))
